# No Exception Authorized
So, where do we have exceptions?

```scala
sealed case class Bank private (private val exchangeRates: Map[String, Double] = Map.empty) {
  ...
  def convert(money: Money, toCurrency: Currency): Money = {
    if (!canConvert(money, toCurrency)) {
      throw MissingExchangeRateException(money.currency, toCurrency)
    }
    convertSafely(money, toCurrency)
  }
  ...
}

sealed class Portfolio(private val moneys: Money*) {
  ...
  private def convertMoney(
      bank: Bank,
      money: Money,
      toCurrency: Currency
  ): ConversionResult = {
    try {
      new ConversionResult(bank.convert(money, toCurrency))
    } catch {
      case missingExchangeRate: MissingExchangeRateException =>
        new ConversionResult(missingExchangeRate)
    }
  }
  ...
}
```

We have a few options to remove exceptions
  - Use Hollywood principle -> callback functions `onSuccess`, `onFailure`
  - Use a data structure representing computation results : `success` or `failure`

What a coincidence! We have already created a similar structure: `ConversionResult`.

Let's see we can go from there.

## Portfolio
We're going to use the same [Wrap Technique](https://understandlegacycode.com/blog/key-points-of-working-effectively-with-legacy-code/#2-the-wrap-technique)  we used before.

:red_circle: You know the drill by now: as usual, we start with a red test at the `Portfolio` level.

We rename the `evaluate` method into `evaluateWithException`.
We use `OptionValues` from `scalatest`.

```scala
class PortfolioShould
    extends AnyFunSuite
    with BeforeAndAfterEach
    with OptionValues {
    ...
    test("5 USD + 10 EUR + 4 EUR = 21.8 USD") {
        assert(
          portfolioWith(
            5.dollars(),
            10.euros(),
            4.euros()
          ).evaluateWithException(bank, USD) == 21.8.dollars()
        )
      }
    
    test(
      "Return a failure in case of missing exchange rates"
    ) {
        assert(
          portfolioWith(
            1.euros(),
            1.dollars(),
            1.koreanWons()
          ).evaluate(bank, EUR)
          .failure
          .value == "Missing exchange rate(s): [USD->EUR],[KRW->EUR]"
        )
    }
}
```

:green_circle: We generate a new `evaluate` method from the test with the expected signature.

```scala
sealed class Portfolio(private val moneys: Money*) {
  def evaluate(bank: Bank, currency: Currency): ConversionResult = ???
  
sealed case class ConversionResult private (
    money: Option[Money],
    missingExchangeRate: Option[MissingExchangeRateException]
) {

  def this(money: Money) = this(Some(money), None)

  def this(missingExchangeRate: MissingExchangeRateException) =
    this(None, Some(missingExchangeRate))

  def failure(): String =
    missingExchangeRate.get.getMessage

  def isFailure: Boolean = missingExchangeRate.isDefined
}
```

Let's implement the `evaluate` by calling the old one first.

```scala
def evaluate(bank: Bank, currency: Currency): ConversionResult =
    try {
      new ConversionResult(evaluateWithException(bank, currency))
    } catch {
      case missingExchangeRatesException: MissingExchangeRatesException =>
        new ConversionResult(missingExchangeRatesException)
    }
```

At the moment, `ConversionResult` is coupled to a specific exception type, but we'd like to have a bit more flexibility here. We need to adapt it to support `Exception` differently.

Let's use scala `generics` for this.

```scala
sealed case class ConversionResult[Failure] private (
    money: Option[Money],
    failure: Option[Failure]
) {

  def this(money: Money) = this(Some(money), None)

  def this(failure: Failure) =
    this(None, Some(failure))

  def isFailure: Boolean = failure.isDefined
}
```

We need to adapt our `Portfolio` to use the Generic type everywhere

```scala
sealed class Portfolio(private val moneys: Money*) {
  def add(money: Money): Portfolio =
    new Portfolio(moneys :+ money: _*)

  def evaluate(bank: Bank, currency: Currency): ConversionResult[String] =
    try {
      new ConversionResult(evaluateWithException(bank, currency))
    } catch {
      case missingExchangeRatesException: MissingExchangeRatesException =>
        new ConversionResult(missingExchangeRatesException.getMessage)
    }

  def evaluateWithException(bank: Bank, toCurrency: Currency): Money = {
    val convertedMoneys = convertMoneys(bank, toCurrency)

    if (containsFailure(convertedMoneys))
      throw toMissingExchangeRatesException(convertedMoneys)
    else toMoney(toCurrency, convertedMoneys)
  }

  private def convertMoneys(
      bank: Bank,
      toCurrency: Currency
  ): Seq[ConversionResult[MissingExchangeRateException]] =
    moneys.map(money => convertMoney(bank, money, toCurrency))

  private def convertMoney(
      bank: Bank,
      money: Money,
      toCurrency: Currency
  ): ConversionResult[MissingExchangeRateException] = {
    try {
      new ConversionResult(bank.convert(money, toCurrency))
    } catch {
      case missingExchangeRate: MissingExchangeRateException =>
        new ConversionResult(missingExchangeRate)
    }
  }

  private def containsFailure(
      convertedMoneys: Seq[ConversionResult[MissingExchangeRateException]]
  ): Boolean =
    convertedMoneys.exists(_.isFailure)

  private def toMissingExchangeRatesException(
      convertedMoneys: Seq[ConversionResult[MissingExchangeRateException]]
  ) =
    MissingExchangeRatesException(
      convertedMoneys
        .flatMap(_.failure)
    )

  private def toMoney(
      toCurrency: Currency,
      convertedMoneys: Seq[ConversionResult[MissingExchangeRateException]]
  ): Money =
    Money(
      convertedMoneys
        .flatMap(_.money)
        .foldLeft(0d)((acc, money) => acc + money.amount),
      toCurrency
    )
}
```

Our test is now green.

:large_blue_circle: Let's refactor by implementing the new evaluation logic.

- We implement the new evaluation logic
  - Because we will have to change method signature we choose to duplicate the code

```scala
  def evaluate(bank: Bank, toCurrency: Currency): ConversionResult[String] = {
    val convertedMoneys = convertMoneys(bank, toCurrency)

    if (containsFailure(convertedMoneys))
      new ConversionResult(
        convertedMoneys
          .flatMap(_.failure)
          .map(e => s"[${e.getMessage}]")
          .mkString("Missing exchange rate(s): ", ",", "")
      )
    else
      new ConversionResult(
        Money(
          convertedMoneys
            .flatMap(_.money)
            .foldLeft(0d)((acc, money) => acc + money.amount),
          toCurrency
        )
      )
  }
```

Let's adapt a first test to use new `evaluate` method as code is no longer throwing an `Exception`.

We need to access `money` from `ConversionResult`.

```scala
  test("5 USD + 10 USD = 15 USD") {
    assert(
      portfolioWith(
        5.dollars(),
        10.dollars()
      ).evaluate(bank, USD).money.value == 15.dollars()
    )
  }
```

Let's adapt all the `Portfolio` tests.

:large_blue_circle: Now is the time to remove dead code and duplication
- Method `evaluateWithException` is no longer used, so aren't its related private methods: `toMissingExchangeRatesException`, `toMoney`.
- The `MissingExchangeRatesException` is no longer used either.
    

We can make some clean up: 
- Extract some methods from the `evaluate` one

```scala
  def evaluate(bank: Bank, toCurrency: Currency): ConversionResult[String] = {
    val convertedMoneys = convertMoneys(bank, toCurrency)

    if (containsFailure(convertedMoneys))
      new ConversionResult(toFailure(convertedMoneys))
    else
      new ConversionResult(sumConvertedMoney(toCurrency, convertedMoneys))
  }

  private def sumConvertedMoney(
      toCurrency: Currency,
      convertedMoneys: Seq[ConversionResult[MissingExchangeRateException]]
  ): Money = {
    Money(
      convertedMoneys
        .flatMap(_.money)
        .foldLeft(0d)((acc, money) => acc + money.amount),
      toCurrency
    )
  }

  private def toFailure(
      convertedMoneys: Seq[ConversionResult[MissingExchangeRateException]]
  ): String = {
    convertedMoneys
      .flatMap(_.failure)
      .map(e => s"[${e.getMessage}]")
      .mkString("Missing exchange rate(s): ", ",", "")
  }
```

:large_blue_circle: We can express success and failure in more visual way so let's try.

```scala
  def evaluate(bank: Bank, toCurrency: Currency): ConversionResult[String] = {
    val convertedMoneys = convertMoneys(bank, toCurrency)

    if (containsFailure(convertedMoneys))
      fromFailure(toFailure(convertedMoneys))
    else
      fromSuccess(sumConvertedMoney(toCurrency, convertedMoneys))
  }

sealed case class ConversionResult[Failure] private (
    money: Option[Money],
    failure: Option[Failure]
) {

  def this(money: Money) = this(Some(money), None)

  def this(failure: Failure) =
    this(None, Some(failure))

  def isFailure: Boolean = failure.isDefined
}

object ConversionResult {
  def fromSuccess[Failure](money: Money): ConversionResult[Failure] =
    new ConversionResult[Failure](money)

  def fromFailure[Failure](failure: Failure): ConversionResult[Failure] =
    new ConversionResult[Failure](failure)
}
```

We have successfully removed one `Exception` but the work is not over yet. 

We need to do the same at the `Bank` level.

## Bank
The strategy we used worked quite well. So, same idea here.

:red_circle: Red.

```scala
  test("Return a failure result in case of missing exchange rate") {
    assert(
      bank.convert(10.euros(), KRW).failure.value == "EUR->KRW"
    )
  }
```

We rename the existing `convert` to `convertWithException` and generate the code from our test.

```scala
  def convert(money: Money, currency: Currency): ConversionResult[String] = ???

  def convertWithException(money: Money, toCurrency: Currency): Money = {
    if (!canConvert(money, toCurrency)) {
      throw MissingExchangeRateException(money.currency, toCurrency)
    }
    convertSafely(money, toCurrency)
  }
```

:green_circle: Green.

```scala
  def convert(money: Money, toCurrency: Currency): ConversionResult[String] = {
    try {
      fromSuccess(convertWithException(money, toCurrency))
    } catch {
      case missingExchangeRateException: MissingExchangeRateException =>
        fromFailure(missingExchangeRateException.getMessage)
    }
  }
```

:large_blue_circle: Refactor.

```scala
  def convert(money: Money, toCurrency: Currency): ConversionResult[String] = {
    if (canConvert(money, toCurrency))
      fromSuccess(convertSafely(money, toCurrency))
    else fromFailure(s"${money.currency}->$toCurrency")
  }
```

We can now adapt our callers to use the new `convert`: `Portfolio` and `BankShould`
  - Really easy in the tests
  - We have some work to refactor the `Porftolio` so we start by changing the `convertMoneys` method

```scala
  private def convertMoneys(
      bank: Bank,
      toCurrency: Currency
  ): Seq[ConversionResult[String]] =
    moneys.map(money => bank.convert(money, toCurrency))

  // Delete it -> not needed anymore
  private def convertMoney(
      bank: Bank,
      money: Money,
      toCurrency: Currency
  ): ConversionResult[String] = {
    try {
      new ConversionResult(bank.convert(money, toCurrency))
    } catch {
      case missingExchangeRate: MissingExchangeRateException =>
        new ConversionResult(missingExchangeRate)
    }
  }
```

We adapt methods in `Portfolio` to only use `ConversionResult<String>`.

```scala
sealed class Portfolio(private val moneys: Money*) {
  def add(money: Money): Portfolio =
    new Portfolio(moneys :+ money: _*)

  def evaluate(bank: Bank, toCurrency: Currency): ConversionResult[String] = {
    val convertedMoneys = convertMoneys(bank, toCurrency)

    if (containsFailure(convertedMoneys))
      fromFailure(toFailure(convertedMoneys))
    else
      fromSuccess(sumConvertedMoney(toCurrency, convertedMoneys))
  }

  private def sumConvertedMoney(
      toCurrency: Currency,
      convertedMoneys: Seq[ConversionResult[String]]
  ): Money = {
    Money(
      convertedMoneys
        .flatMap(_.money)
        .foldLeft(0d)((acc, money) => acc + money.amount),
      toCurrency
    )
  }

  private def toFailure(
      convertedMoneys: Seq[ConversionResult[String]]
  ): String = {
    convertedMoneys
      .flatMap(_.failure)
      .map(failure => s"[$failure]")
      .mkString("Missing exchange rate(s): ", ",", "")
  }

  private def convertMoneys(
      bank: Bank,
      toCurrency: Currency
  ): Seq[ConversionResult[String]] =
    moneys.map(money => bank.convert(money, toCurrency))

  private def containsFailure(
      convertedMoneys: Seq[ConversionResult[String]]
  ): Boolean =
    convertedMoneys.exists(_.isFailure)
}
```

We can now remove the `convertWithException` method in `Bank` and `MissingExchangeRateException`

## Reflect
![No exception](../../docs/img/no-exception.png)

Any improvement ideas?
  - The way we use the `ConversionResult` is not safe for example...
  - Maybe there is an alternative to use safer data structure
  - Use `Either` monad for example