  # No Exception Authorized

So, where do we have exceptions?

```c#
public class Bank {
    ...
    public Money Convert(Money money, Currency to) =>
    CanConvert(money.Currency, to)
        ? ConvertSafely(money, to)
        : throw new MissingExchangeRateException(money.Currency, to);
    ...
}

public class Portfolio {
    ...

    private static ConversionResult ConvertMoney(Bank bank, Currency currency, Money money)
    {
        try
        {
            return new ConversionResult(bank.Convert(money, currency));
        }
        catch (MissingExchangeRateException exception)
        {
            return new ConversionResult(exception);
        }
    }
    ...
}
```

There a multiple ways to remove exceptions:
  - Using the `Hollywood principle` -> callback functions `OnSuccess`, `OnFailure`
  - Using a data structure representing computation results -> `Success` or `Failure`

What a coincidence! We have already created a similar structure: `ConversionResult`.

Let's see we can go from there.

## Portfolio
We're going to use the same [Wrap Technique](https://understandlegacycode.com/blog/key-points-of-working-effectively-with-legacy-code/#2-the-wrap-technique)  we used before.

:red_circle: You know the drill by now: as usual, we start with a red test at the `Portfolio` level.

We rename the `Evaluate` method into `EvaluateWithException`.

```c#
[Fact(DisplayName = "5 USD + 10 EUR + 4 EUR = 21.8 USD")]
public void Add_ShouldAddMoneyInDollarsAndMultipleAmountInEuros() =>
    PortfolioWith(new Money(5, Currency.USD), new Money(10, Currency.EUR), new Money(4, Currency.EUR))
        .EvaluateWithException(bank, Currency.USD)
        .Should()
        .Be(new Money(21.8, Currency.USD));

[Fact(DisplayName = "Throws a MissingExchangeRatesException in case of missing exchange rates")]
public void Add_ShouldThrowAMissingExchangeRatesException()
{
    PortfolioWith(new Money(1, Currency.EUR), new Money(1, Currency.USD), new Money(1, Currency.KRW))
        .Evaluate(this.bank, Currency.EUR)
        .Failure
        .Should()
        .Be("Missing exchange rate(s): [USD->EUR],[KRW->EUR]");
}
```

:green_circle: We generate a new `Evaluate` method from the test with the expected signature.

We need to change `ConversionResult` accessibility as well.

```c#
public ConversionResult Evaluate(Bank bank, Currency eur)
{
    throw new NotImplementedException();
}

public class ConversionResult
{
}
```

We implement the new `Evaluate` method by calling the old one first.

```c#
public ConversionResult Evaluate(Bank bank, Currency currency)
{
    try {
        return new ConversionResult(
            this.EvaluateWithException(bank, currency)
        );
    } catch (MissingExchangeRatesException exception) {
        return new ConversionResult(exception);
    }
}
```

At the moment, `ConversionResult` is coupled to a specific exception type, but we'd like to have a bit more flexibility here. We need to adapt it to support `Exception` differently.

Let's use C# `generics` for this.

```c#
public class ConversionResult<T>
{
    public Money? Money { get; }

    public T? Failure { get; }
    
    public ConversionResult(Money money)
    {
        this.Money = money;
    }

    public ConversionResult(T failure)
    {
        this.Failure = failure;
    }

    public bool IsFailure() => this.Failure is { };

    public bool IsSuccess() => this.Money is { };
}
```

We need to adapt our `Portfolio` to use the Generic type everywhere.

```c#
public class Portfolio
{
    public Money EvaluateWithException(Bank bank, Currency currency)
    {
        List<ConversionResult<MissingExchangeRateException>> results = this.GetConvertedMoneys(bank, currency);
        return ContainsFailure(results)
            ? throw ToException(results)
            : ToMoney(results, currency);
    }

    private static MissingExchangeRatesException ToException(
        IEnumerable<ConversionResult<MissingExchangeRateException>> results) =>
        new(results
            .Where(result => result.IsFailure())
            .Select(result => result.Failure!)
            .ToList());

    private static Money ToMoney(IEnumerable<ConversionResult<MissingExchangeRateException>> results,
        Currency currency) =>
        new(results.Sum(result => result.Money!.Amount), currency);

    private static bool ContainsFailure(IEnumerable<ConversionResult<MissingExchangeRateException>> results) =>
        results.Any(result => result.IsFailure());

    private List<ConversionResult<MissingExchangeRateException>> GetConvertedMoneys(Bank bank, Currency currency) =>
        this.moneys
            .Select(money => ConvertMoney(bank, currency, money))
            .ToList();

    private static ConversionResult<MissingExchangeRateException> ConvertMoney(Bank bank, Currency currency,
        Money money)
    {
        try
        {
            return new ConversionResult<MissingExchangeRateException>(bank.Convert(money, currency));
        }
        catch (MissingExchangeRateException exception)
        {
            return new ConversionResult<MissingExchangeRateException>(exception);
        }
    }

    public ConversionResult<string> Evaluate(Bank bank, Currency currency)
    {
        try
        {
            return new ConversionResult<string>(
                this.EvaluateWithException(bank, currency)
            );
        }
        catch (MissingExchangeRatesException exception)
        {
            return new ConversionResult<string>(exception.Message);
        }
    }
}
```

Our test is now green.

:large_blue_circle: Let's refactor by implementing the new evaluation logic.

```c#
private static string GetMissingRates(IEnumerable<MissingExchangeRateException> missingRates) => missingRates
    .Select(exception => $"[{exception.Message}]")
    .Aggregate((r1, r2) => $"{r1},{r2}");

public ConversionResult<string> Evaluate(Bank bank, Currency currency)
{
    List<ConversionResult<MissingExchangeRateException>> results = this.GetConvertedMoneys(bank, currency);
    if (ContainsFailure(results))
    {
        return new ConversionResult<string>($"Missing exchange rate(s): {GetMissingRates(results.Where(result => result.IsFailure()).Select(result => result.Failure!))}");
    }

    return new ConversionResult<string>(new Money(results
        .Where(result => result.IsSuccess())
        .Sum(result => result.Money!.Amount), currency));
}
```

Let's adapt a first test to use new `Evaluate` method as code is no longer throwing an `Exception`.

We need to access `Money` from `ConversionResult`.

```c#
[Fact(DisplayName = "5 USD + 10 USD = 15 USD")]
public void Add_ShouldAddMoneyInTheSameCurrency()
{
    PortfolioWith(new Money(5, Currency.USD), new Money(10, Currency.USD))
        .Evaluate(bank, Currency.USD).Money.Should().Be(new Money(15, Currency.USD));
}
```

:large_blue_circle: Now is the time to remove dead code and duplication
  - Method `EvaluateWithException` is no longer used, so aren't its related private methods: `ToException`, `ToMoney`.
  - The `MissingExchangeRatesException` is no longer used either.

We can make some clean up: 
  - Extract inner public class in its own file
  - Extract some methods from the `Evaluate` one.

```c#
public ConversionResult<string> Evaluate(Bank bank, Currency currency)
{
  List<ConversionResult<MissingExchangeRateException>> results = this.GetConvertedMoneys(bank, currency);
  return ContainsFailure(results) ? this.ToFailure(results) : this.ToSuccess(results, currency);
}

private ConversionResult<string> ToFailure(IEnumerable<ConversionResult<MissingExchangeRateException>> results) =>
    new ConversionResult<string>($"Missing exchange rate(s): {GetMissingRates(results.Where(result => result.IsFailure()).Select(result => result.Failure!))}");

private ConversionResult<string> ToSuccess(IEnumerable<ConversionResult<MissingExchangeRateException>> results, Currency currency) =>
    new ConversionResult<string>(new Money(results
        .Where(result => result.IsSuccess())
        .Sum(result => result.Money!.Amount), currency));
```

:large_blue_circle: We can express success and failure in more visual way so let's try.

```c#
public ConversionResult<string> Evaluate(Bank bank, Currency currency)
{
    List<ConversionResult<MissingExchangeRateException>> results = this.GetConvertedMoneys(bank, currency);
    return ContainsFailure(results) ? ConversionResult<string>.FromFailure(this.ToFailure(results)) : ConversionResult<string>.FromMoney(this.ToSuccess(results, currency));
}

private string ToFailure(IEnumerable<ConversionResult<MissingExchangeRateException>> results) =>
    $"Missing exchange rate(s): {GetMissingRates(results.Where(result => result.IsFailure()).Select(result => result.Failure!))}";

private Money ToSuccess(IEnumerable<ConversionResult<MissingExchangeRateException>> results, Currency currency) =>
    new Money(results.Where(result => result.IsSuccess()).Sum(result => result.Money!.Amount), currency);

public class ConversionResult<T>
{
    public ConversionResult(Money money)
    {
        this.Money = money;
    }

    public ConversionResult(T failure)
    {
        this.Failure = failure;
    }

    public Money? Money { get; }

    public T? Failure { get; }

    public bool IsFailure() => this.Failure is { };

    public bool IsSuccess() => this.Money is { };

    public static ConversionResult<T> FromFailure(T failure) => new ConversionResult<T>(failure);

    public static ConversionResult<T> FromMoney(Money money) => new ConversionResult<T>(money);
}
```

We have successfully removed one `Exception` but the work is not over yet. 

We need to do the same at the `Bank` level.

## Bank

The strategy we used worked quite well. So, same idea here.

:red_circle: Red.

```c#
[Fact(DisplayName = "Throws a MissingExchangeRateException in case of missing exchange rates")]
public void ReturnsFailureResultGivenMissingExchangeRate()
{
    this._bank.Convert(new Money(10, EUR), KRW)
        .Failure
        .Should()
        .Be("EUR->KRW");
}
```

We rename the existing `Convert` to `ConvertWithException` and generate the code from our test.

```c#
public Money ConvertWithException(Money money, Currency to) =>
    CanConvert(money.Currency, to)
        ? ConvertSafely(money, to)
        : throw new MissingExchangeRateException(money.Currency, to);

public ConversionResult<string> Convert(Money money, Currency currency)
{
    throw new NotImplementedException();
}
```

:green_circle: Green.

```c#
public ConversionResult<string> Convert(Money money, Currency currency)
{
    try
    {
        return ConversionResult<string>.FromMoney(this.ConvertWithException(money, currency));
    }
    catch (Exception exception)
    {
        return ConversionResult<string>.FromFailure(exception.Message);
    }
}
```

:large_blue_circle: Refactor.

```c#
public ConversionResult<string> Convert(Money money, Currency to) =>
    this.CanConvert(money.Currency, to)
        ? ConversionResult<string>.FromMoney(ConvertSafely(money, to))
        : ConversionResult<string>.FromFailure($"{money.Currency}->{to}");
```

We can now adapt our callers to use the new `Convert`: `Portfolio` and `BankShould`
  - Really easy in the tests
  - We have some work to refactor the `Porftolio` so we start by changing the `convertAllMoneys` method

```c#
// Delete it -> not needed anymore
private static ConversionResult<MissingExchangeRateException> ConvertMoney(Bank bank, Currency currency,
    Money money)
{
    try
    {
        return new ConversionResult<MissingExchangeRateException>(bank.Convert(money, currency));
    }
    catch (MissingExchangeRateException exception)
    {
        return new ConversionResult<MissingExchangeRateException>(exception);
    }
}
```

We adapt methods in `Portfolio` to only use `ConversionResult<String>`.

```c#
private static bool ContainsFailure(IEnumerable<ConversionResult<string>> results) =>
    results.Any(result => result.IsFailure());

private List<ConversionResult<string>> GetConvertedMoneys(Bank bank, Currency currency) =>
    this.moneys
        .Select(money => bank.Convert(money, currency))
        .ToList();

public Portfolio Add(Money money)
{
    List<Money> updatedMoneys = this.moneys.ToList();
    updatedMoneys.Add(money);
    return new Portfolio(updatedMoneys);
}

private static string GetMissingRates(IEnumerable<string> missingRates) => missingRates
    .Select(value => $"[{value}]")
    .Aggregate((r1, r2) => $"{r1},{r2}");

public ConversionResult<string> Evaluate(Bank bank, Currency currency)
{
    var results = this.GetConvertedMoneys(bank, currency);
    return ContainsFailure(results)
        ? ConversionResult<string>.FromFailure(this.ToFailure(results))
        : ConversionResult<string>.FromMoney(this.ToSuccess(results, currency));
}

private string ToFailure(IEnumerable<ConversionResult<string>> results) =>
    $"Missing exchange rate(s): {GetMissingRates(results.Where(result => result.IsFailure()).Select(result => result.Failure!))}";

private Money ToSuccess(IEnumerable<ConversionResult<string>> results, Currency currency) =>
    new(results.Where(result => result.IsSuccess()).Sum(result => result.Money!.Amount), currency);
```

We can now remove the `ConvertWithException` method in `Bank` and `MissingExchangeRateException`.

## Reflect
![No exception](../../docs/img/no-exception.png)

Any improvement ideas?
  - The way we use the `ConversionResult` is not safe for example...
  - Maybe there is an alternative to use safer data structure
  - You can discover more about the `Monad` concepts and how to apply them in C# with [language-ext](https://github.com/louthy/language-ext)